(function () {
  'use strict';
  var STORAGE_KEY='educonect:module:cie-404';
  var SYSTEMS={skeletal:'Sistema óseo',respiratory:'Sistema respiratorio',circulatory:'Sistema circulatorio',digestive:'Sistema digestivo'};
  var ORGANS=[
    {id:'skull',name:'Cráneo',icon:'💀',system:'skeletal',description:'Conjunto de huesos que forma la cabeza y protege el encéfalo.',fn:'Proteger el cerebro y sostener la cara',location:'Cabeza',care:'Usa protección adecuada al montar bicicleta o practicar deportes.'},
    {id:'spine',name:'Columna vertebral',icon:'🦴',system:'skeletal',description:'Cadena flexible de vértebras que sostiene el tronco y rodea la médula espinal.',fn:'Sostener el cuerpo y permitir movimiento',location:'Desde el cuello hasta la pelvis',care:'Una postura variada y músculos fuertes ayudan a cuidarla.'},
    {id:'ribs',name:'Caja torácica',icon:'🩻',system:'skeletal',description:'Costillas unidas a la columna y al esternón que rodean el tórax.',fn:'Proteger corazón y pulmones',location:'Tórax',care:'La actividad física fortalece huesos y músculos respiratorios.'},
    {id:'pelvis',name:'Pelvis',icon:'🦴',system:'skeletal',description:'Anillo óseo que conecta el tronco con las extremidades inferiores.',fn:'Sostener órganos y transferir el peso',location:'Parte inferior del tronco',care:'Evita cargar peso con posturas forzadas.'},
    {id:'trachea',name:'Tráquea',icon:'🫁',system:'respiratory',description:'Conducto con anillos cartilaginosos por el que circula el aire.',fn:'Conducir aire hacia y desde los pulmones',location:'Cuello y centro del tórax',care:'Evitar humo protege sus tejidos y los pulmones.'},
    {id:'lungs',name:'Pulmones',icon:'🫁',system:'respiratory',description:'Órganos esponjosos donde el oxígeno pasa a la sangre y sale dióxido de carbono.',fn:'Realizar el intercambio de gases',location:'A ambos lados del corazón',care:'El aire limpio y no fumar preservan su capacidad.'},
    {id:'diaphragm',name:'Diafragma',icon:'🌬️',system:'respiratory',description:'Músculo en forma de cúpula que cambia el volumen del tórax al respirar.',fn:'Impulsar la entrada y salida de aire',location:'Debajo de los pulmones',care:'La respiración profunda permite reconocer su movimiento.'},
    {id:'heart',name:'Corazón',icon:'🫀',system:'circulatory',description:'Músculo hueco que impulsa la sangre por dos circuitos principales.',fn:'Bombear sangre',location:'Centro del tórax, ligeramente a la izquierda',care:'El movimiento diario ayuda a cuidar el sistema circulatorio.'},
    {id:'arteries',name:'Arterias',icon:'🔴',system:'circulatory',description:'Vasos que llevan la sangre desde el corazón hacia los tejidos.',fn:'Distribuir sangre desde el corazón',location:'Por todo el organismo',care:'Actividad física y alimentación equilibrada cuidan los vasos.'},
    {id:'veins',name:'Venas',icon:'🔵',system:'circulatory',description:'Vasos que retornan la sangre desde los tejidos hacia el corazón.',fn:'Devolver sangre al corazón',location:'Por todo el organismo',care:'Mover las piernas favorece el retorno venoso.'},
    {id:'esophagus',name:'Esófago',icon:'↘️',system:'digestive',description:'Tubo muscular que lleva el alimento desde la garganta hasta el estómago.',fn:'Transportar el alimento',location:'Detrás de la tráquea',care:'Comer despacio facilita una deglución segura.'},
    {id:'stomach',name:'Estómago',icon:'🫃',system:'digestive',description:'Bolsa muscular que mezcla alimentos con sustancias digestivas.',fn:'Mezclar e iniciar la digestión',location:'Parte superior izquierda del abdomen',care:'Horarios regulares y porciones adecuadas favorecen la digestión.'},
    {id:'liver',name:'Hígado',icon:'🟤',system:'digestive',description:'Órgano que procesa nutrientes, produce bilis y participa en la eliminación de sustancias.',fn:'Procesar nutrientes y producir bilis',location:'Parte superior derecha del abdomen',care:'Evitar sustancias tóxicas ayuda a protegerlo.'},
    {id:'intestines',name:'Intestinos',icon:'〰️',system:'digestive',description:'El intestino delgado absorbe nutrientes; el grueso recupera agua y forma las heces.',fn:'Absorber nutrientes y agua',location:'Centro e inferior del abdomen',care:'Agua, fibra y movimiento favorecen su funcionamiento.'}
  ];
  var MISSIONS=[
    {system:'circulatory',id:'heart',title:'Encuentra la bomba del cuerpo',hint:'Selecciona el músculo que impulsa la sangre.'},
    {system:'respiratory',id:'lungs',title:'Localiza el intercambio de gases',hint:'Selecciona los órganos que incorporan oxígeno.'},
    {system:'skeletal',id:'ribs',title:'Busca la protección del tórax',hint:'Selecciona los huesos que rodean corazón y pulmones.'},
    {system:'digestive',id:'stomach',title:'Encuentra el mezclador digestivo',hint:'Selecciona el órgano que mezcla el alimento.'},
    {system:'digestive',id:'intestines',title:'Localiza la absorción',hint:'Selecciona las estructuras donde se absorben nutrientes y agua.'},
    {system:'skeletal',id:'spine',title:'Encuentra el eje del cuerpo',hint:'Selecciona la cadena ósea que sostiene el tronco.'}
  ];
  var JOURNEY=[
    {system:'respiratory',id:'trachea',text:'1. El aire entra y avanza por las vías respiratorias hasta la tráquea.'},
    {system:'respiratory',id:'lungs',text:'2. En los pulmones, el oxígeno atraviesa superficies muy delgadas y entra en la sangre.'},
    {system:'circulatory',id:'heart',text:'3. El corazón impulsa la sangre oxigenada hacia el resto del cuerpo.'},
    {system:'circulatory',id:'arteries',text:'4. Las arterias distribuyen esa sangre hacia los diferentes tejidos.'},
    {system:'circulatory',id:'veins',text:'5. La sangre regresa por las venas para repetir el circuito y eliminar dióxido de carbono.'}
  ];
  var QUESTIONS=[
    {q:'¿Dónde ocurre el intercambio de oxígeno?',options:['Estómago','Pulmones','Hígado','Columna'],answer:'Pulmones'},
    {q:'¿Qué sistema transporta oxígeno y nutrientes?',options:['Óseo','Digestivo','Circulatorio','Respiratorio'],answer:'Circulatorio'},
    {q:'¿Qué protege el cerebro?',options:['Pelvis','Cráneo','Costillas','Diafragma'],answer:'Cráneo'},
    {q:'¿Qué órgano produce bilis y procesa nutrientes?',options:['Hígado','Corazón','Pulmón','Estómago'],answer:'Hígado'},
    {q:'¿Qué músculo ayuda a introducir aire en los pulmones?',options:['Corazón','Diafragma','Estómago','Esófago'],answer:'Diafragma'},
    {q:'¿Dónde se absorbe la mayor parte de los nutrientes?',options:['Tráquea','Intestino delgado','Esófago','Venas'],answer:'Intestino delgado'}
  ];
  var state=loadState(),dom={},scene,camera,renderer,modelRoot,bodyGroup,raycaster,pointer,animationId=0;
  var systemGroups={},objects=[],labels=[],bodyMaterials=[],selected='heart',filter='all',rotationX=-.08,rotationY=.25,distance=25,autoRotate=!matchMedia('(prefers-reduced-motion: reduce)').matches,dragging=false,moved=false,startX=0,startY=0,pinch=0;

  function $(id){return document.getElementById(id);}function organ(id){return ORGANS.find(function(x){return x.id===id;})||ORGANS[7];}
  function loadState(){try{var d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return{mission:Math.min(Number(d.mission)||0,MISSIONS.length),quiz:Math.min(Number(d.quiz)||0,QUESTIONS.length),correct:Number(d.correct)||0,journey:Math.min(Number(d.journey)||0,JOURNEY.length-1),journeyDone:!!d.journeyDone,selected:d.selected||'heart'};}catch(_){return{mission:0,quiz:0,correct:0,journey:0,journeyDone:false,selected:'heart'};}}
  function save(){state.selected=selected;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateProgress();}
  function updateProgress(){var done=state.mission+state.quiz+(state.journeyDone?1:0),total=MISSIONS.length+QUESTIONS.length+1,pct=Math.round(done/total*100);dom.progressText.textContent=pct+'%';dom.progressBar.style.width=pct+'%';}
  function cache(){['progressText','progressBar','viewerTitle','scene','labels','fallback','bodyToggle','labelsToggle','opacityRange','organButtons','organSystem','organName','organDescription','organFunction','organLocation','organCare','journeyText','journeyPrev','journeyNext','journeyStep','missionTitle','missionHint','missionStatus','question','answers','feedback','rotateButton','resetButton'].forEach(function(id){dom[id]=$(id);});}
  function mat(color,transparent,opacity){return new THREE.MeshStandardMaterial({color:color,roughness:.64,metalness:.03,transparent:!!transparent,opacity:opacity===undefined?1:opacity,depthWrite:!transparent,side:transparent?THREE.DoubleSide:THREE.FrontSide});}
  function add(group,id,geometry,material,pos,scale,rot,label){var m=new THREE.Mesh(geometry,material);m.position.set(pos[0],pos[1],pos[2]);if(scale)m.scale.set(scale[0],scale[1],scale[2]);if(rot)m.rotation.set(rot[0],rot[1],rot[2]);m.userData.organId=id;group.add(m);if(id){objects.push({id:id,system:organ(id).system,mesh:m});if(label)addLabel(id,label,m);}return m;}
  function addLabel(id,text,mesh){var el=document.createElement('span');el.className='label';el.textContent=text;dom.labels.appendChild(el);labels.push({id:id,el:el,mesh:mesh});}
  function cylinderBetween(group,id,a,b,radius,material){var start=new THREE.Vector3(a[0],a[1],a[2]),end=new THREE.Vector3(b[0],b[1],b[2]),mid=start.clone().add(end).multiplyScalar(.5),length=start.distanceTo(end),mesh=add(group,id,new THREE.CylinderGeometry(radius,radius,length,10),material,[mid.x,mid.y,mid.z]);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),end.clone().sub(start).normalize());return mesh;}
  function line(group,id,points,color,width){var geometry=new THREE.BufferGeometry().setFromPoints(points.map(function(p){return new THREE.Vector3(p[0],p[1],p[2]);})),material=new THREE.LineBasicMaterial({color:color,linewidth:width||1});var mesh=new THREE.Line(geometry,material);mesh.userData.organId=id;group.add(mesh);objects.push({id:id,system:organ(id).system,mesh:mesh});return mesh;}
  function buildBody(){bodyGroup=new THREE.Group();modelRoot.add(bodyGroup);var skin=mat(0xf0b29b,true,Number(dom.opacityRange.value));bodyMaterials.push(skin);add(bodyGroup,null,new THREE.SphereGeometry(1.75,24,18),skin,[0,8.5,0],[1,.95,.9]);add(bodyGroup,null,new THREE.CylinderGeometry(2.25,2.9,6.4,20),skin,[0,4.1,0],[1,1,.62]);add(bodyGroup,null,new THREE.SphereGeometry(2.65,22,16),skin,[0,.55,0],[1,.8,.63]);cylinderBetween(bodyGroup,null,[-2.2,6.2,0],[-4.2,1.4,0],.62,skin);cylinderBetween(bodyGroup,null,[2.2,6.2,0],[4.2,1.4,0],.62,skin);cylinderBetween(bodyGroup,null,[-1.25,-.9,0],[-1.35,-7.5,0],.84,skin);cylinderBetween(bodyGroup,null,[1.25,-.9,0],[1.35,-7.5,0],.84,skin);}
  function buildSkeleton(g){var bone=mat(0xf1e1bf);var skull=add(g,'skull',new THREE.SphereGeometry(1.42,20,16),bone,[0,8.55,.05],[1,.93,.88],null,'Cráneo');add(g,'skull',new THREE.BoxGeometry(1.25,.85,1.1),bone,[0,7.55,.1]);var spine=cylinderBetween(g,'spine',[0,7,0],[0,-.2,0],.18,bone);addLabel('spine','Columna',spine);for(var y=6.25;y>2.2;y-=.63){var width=2.0-(6.25-y)*.16;var left=new THREE.TorusGeometry(width,.09,7,22,Math.PI*.9);add(g,'ribs',left,bone,[0,y,0],[1,1,.62],[Math.PI/2,0,.15]);}addLabel('ribs','Costillas',objects[objects.length-1].mesh);var pelvis=add(g,'pelvis',new THREE.TorusGeometry(1.6,.32,10,28,Math.PI*1.55),bone,[0,.2,0],[1,.78,.8],[Math.PI/2,0,.8],'Pelvis');cylinderBetween(g,'ribs',[-1.5,6.1,0],[-3.9,1.5,0],.16,bone);cylinderBetween(g,'ribs',[1.5,6.1,0],[3.9,1.5,0],.16,bone);cylinderBetween(g,'pelvis',[-1.05,-.4,0],[-1.3,-7.6,0],.23,bone);cylinderBetween(g,'pelvis',[1.05,-.4,0],[1.3,-7.6,0],.23,bone);return pelvis;}
  function buildRespiratory(g){var airway=mat(0x79d3e5),lungMat=mat(0xf28fa7,true,.82);var trachea=cylinderBetween(g,'trachea',[0,7.4,.25],[0,4.9,.25],.24,airway);addLabel('trachea','Tráquea',trachea);cylinderBetween(g,'trachea',[0,5,.25],[-1.15,4,.25],.15,airway);cylinderBetween(g,'trachea',[0,5,.25],[1.15,4,.25],.15,airway);var left=add(g,'lungs',new THREE.SphereGeometry(1.45,22,16),lungMat,[-1.25,4,.15],[.86,1.55,.62],null,'Pulmones');add(g,'lungs',new THREE.SphereGeometry(1.45,22,16),lungMat,[1.25,4,.15],[.86,1.55,.62]);var dia=add(g,'diaphragm',new THREE.SphereGeometry(2.45,22,12,0,Math.PI*2,0,Math.PI/2),mat(0xd485bb,true,.72),[0,1.75,.1],[1,.34,.66],[Math.PI,0,0],'Diafragma');return left||dia;}
  function buildCirculatory(g){var heartMat=mat(0xd93655),artery=mat(0xe95058),vein=mat(0x397ed3);var h1=add(g,'heart',new THREE.SphereGeometry(.82,20,16),heartMat,[-.36,3.65,1],[.9,1.25,.75],[0,0,-.25],'Corazón');add(g,'heart',new THREE.SphereGeometry(.76,20,16),heartMat,[.33,3.68,1],[.85,1.18,.72],[0,0,.2]);var art=cylinderBetween(g,'arteries',[0,4.4,.72],[0,-5.8,.7],.13,artery);addLabel('arteries','Arterias',art);line(g,'arteries',[[0,4.4,.72],[-2.7,5.8,.55],[-4,1.5,.45]],0xe95058);line(g,'arteries',[[0,.1,.72],[-1.2,-2.5,.6],[-1.3,-7.2,.45]],0xe95058);line(g,'arteries',[[0,.1,.72],[1.2,-2.5,.6],[1.3,-7.2,.45]],0xe95058);var veins=cylinderBetween(g,'veins',[.35,4.2,.35],[.35,-5.7,.35],.11,vein);addLabel('veins','Venas',veins);line(g,'veins',[[.35,4,.35],[2.8,5.7,.3],[4.1,1.5,.2]],0x397ed3);line(g,'veins',[[.35,.2,.35],[-.8,-2.5,.25],[-.95,-7.2,.2]],0x397ed3);line(g,'veins',[[.35,.2,.35],[1.6,-2.5,.25],[1.65,-7.2,.2]],0x397ed3);return h1;}
  function buildDigestive(g){var digestive=mat(0xd58a5c),liverMat=mat(0x8d463b),gutMat=mat(0xe4a36c);var eso=cylinderBetween(g,'esophagus',[0,7.1,-.1],[0,2.55,-.1],.17,digestive);addLabel('esophagus','Esófago',eso);var stomach=add(g,'stomach',new THREE.SphereGeometry(1.05,22,16),digestive,[-.72,1.45,.6],[1.15,1.45,.68],[0,0,-.42],'Estómago');var liver=add(g,'liver',new THREE.SphereGeometry(1.35,22,16),liverMat,[.9,1.55,.15],[1.5,.63,.78],[0,0,-.12],'Hígado');var gut=new THREE.Group();gut.userData.organId='intestines';g.add(gut);objects.push({id:'intestines',system:'digestive',mesh:gut});for(var row=0;row<5;row++){var y=.2-row*.57;var curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-1.35,y,.65),new THREE.Vector3(-.55,y+(row%2?.24:-.24),1),new THREE.Vector3(.55,y+(row%2?-.24:.24),1),new THREE.Vector3(1.35,y,.65)]);var tube=new THREE.Mesh(new THREE.TubeGeometry(curve,28,.16,8,false),gutMat);tube.userData.organId='intestines';gut.add(tube);}addLabel('intestines','Intestinos',gut);return stomach||liver;}
  function buildModel(){modelRoot=new THREE.Group();scene.add(modelRoot);buildBody();['skeletal','respiratory','circulatory','digestive'].forEach(function(key){systemGroups[key]=new THREE.Group();modelRoot.add(systemGroups[key]);});buildSkeleton(systemGroups.skeletal);buildRespiratory(systemGroups.respiratory);buildCirculatory(systemGroups.circulatory);buildDigestive(systemGroups.digestive);}
  function renderOrganButtons(){dom.organButtons.innerHTML='';var list=filter==='all'?ORGANS:ORGANS.filter(function(x){return x.system===filter;});list.forEach(function(item){var b=document.createElement('button');b.type='button';b.dataset.organ=item.id;b.textContent=item.icon+' '+item.name;b.addEventListener('click',function(){selectOrgan(item.id,true);});dom.organButtons.appendChild(b);});}
  function selectOrgan(id,countMission){var item=organ(id);selected=id;if(filter!=='all'&&filter!==item.system)setFilter(item.system);dom.organSystem.textContent=SYSTEMS[item.system];dom.organSystem.style.background=item.system==='skeletal'?'var(--bone)':item.system==='respiratory'?'var(--blue)':item.system==='circulatory'?'var(--red)':'var(--gold)';dom.organName.textContent=item.name;dom.organDescription.textContent=item.description;dom.organFunction.textContent=item.fn;dom.organLocation.textContent=item.location;dom.organCare.textContent='💡 '+item.care;Array.prototype.forEach.call(dom.organButtons.children,function(b){b.classList.toggle('active',b.dataset.organ===id);});objects.forEach(function(x){if(x.mesh.material&&x.mesh.material.emissive)x.mesh.material.emissive.setHex(x.id===id?0x333333:0);});if(countMission&&state.mission<MISSIONS.length&&MISSIONS[state.mission].id===id){state.mission++;dom.missionStatus.textContent='✓ ¡Misión cumplida!';dom.missionStatus.className='status success';save();setTimeout(renderMission,750);}save();}
  function setFilter(next){filter=next;document.querySelectorAll('[data-system]').forEach(function(b){b.classList.toggle('active',b.dataset.system===next);});Object.keys(systemGroups).forEach(function(k){systemGroups[k].visible=next==='all'||next===k;});dom.viewerTitle.textContent=next==='all'?'Vista general':SYSTEMS[next];renderOrganButtons();var current=organ(selected);if(next!=='all'&&current.system!==next)selected=ORGANS.find(function(x){return x.system===next;}).id;selectOrgan(selected,false);updateLabels();}
  function renderMission(){if(state.mission>=MISSIONS.length){dom.missionTitle.textContent='¡Mapa corporal completado!';dom.missionHint.textContent='Identificaste estructuras de los cuatro sistemas.';dom.missionStatus.textContent='6 de 6 misiones';dom.missionStatus.className='status success';return;}var m=MISSIONS[state.mission];dom.missionTitle.textContent=m.title;dom.missionHint.textContent=m.hint;dom.missionStatus.textContent='Misión '+(state.mission+1)+' de '+MISSIONS.length;dom.missionStatus.className='status';}
  function renderJourney(){var step=JOURNEY[state.journey];dom.journeyText.textContent=step.text;dom.journeyStep.textContent=(state.journey+1)+' / '+JOURNEY.length;dom.journeyPrev.disabled=state.journey===0;dom.journeyNext.textContent=state.journey===JOURNEY.length-1?'✓':'→';setFilter(step.system);selectOrgan(step.id,false);save();}
  function renderQuestion(){dom.answers.innerHTML='';dom.feedback.textContent='';if(state.quiz>=QUESTIONS.length){dom.question.textContent='¡Reto completado!';dom.feedback.textContent='Resultado: '+state.correct+' de '+QUESTIONS.length+' respuestas correctas.';var reset=document.createElement('button');reset.type='button';reset.textContent='Repetir';reset.addEventListener('click',function(){state.quiz=0;state.correct=0;save();renderQuestion();});dom.answers.appendChild(reset);return;}var q=QUESTIONS[state.quiz];dom.question.textContent=q.q;q.options.forEach(function(option){var b=document.createElement('button');b.type='button';b.textContent=option;b.addEventListener('click',function(){var right=option===q.answer;b.classList.add(right?'correct':'wrong');dom.feedback.textContent=right?'✓ ¡Correcto!':'Respuesta correcta: '+q.answer+'.';Array.prototype.forEach.call(dom.answers.children,function(x){x.disabled=true;});state.quiz++;if(right)state.correct++;save();setTimeout(renderQuestion,850);});dom.answers.appendChild(b);});}
  function initThree(){if(!window.THREE)throw new Error('Three.js no disponible');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.1,100);renderer=new THREE.WebGLRenderer({antialias:!(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4),alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setClearColor(0,0);dom.scene.insertBefore(renderer.domElement,dom.labels);renderer.domElement.setAttribute('aria-hidden','true');scene.add(new THREE.HemisphereLight(0xd9ecff,0x172038,1.2));var light=new THREE.DirectionalLight(0xffffff,1.5);light.position.set(7,12,12);scene.add(light);var rim=new THREE.PointLight(0xff6680,.7,45);rim.position.set(-7,4,8);scene.add(rim);raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();buildModel();bindScene();resize();animate();}
  function bindScene(){var c=renderer.domElement;c.addEventListener('pointerdown',function(e){dragging=true;moved=false;startX=e.clientX;startY=e.clientY;c.setPointerCapture(e.pointerId);});c.addEventListener('pointermove',function(e){if(!dragging)return;var dx=e.clientX-startX,dy=e.clientY-startY;if(Math.abs(dx)+Math.abs(dy)>3)moved=true;rotationY+=dx*.007;rotationX=Math.max(-.85,Math.min(.85,rotationX+dy*.006));startX=e.clientX;startY=e.clientY;});c.addEventListener('pointerup',function(e){dragging=false;if(!moved)pick(e);});c.addEventListener('wheel',function(e){e.preventDefault();distance=Math.max(18,Math.min(36,distance+e.deltaY*.02));},{passive:false});c.addEventListener('touchstart',function(e){if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);},{passive:true});c.addEventListener('touchmove',function(e){if(e.touches.length===2){var n=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);distance=Math.max(18,Math.min(36,distance+(pinch-n)*.03));pinch=n;}},{passive:true});}
  function pick(e){var rect=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-rect.left)/rect.width*2-1;pointer.y=-(e.clientY-rect.top)/rect.height*2+1;raycaster.setFromCamera(pointer,camera);var candidates=[];objects.forEach(function(x){if(x.mesh.visible&&systemGroups[x.system].visible){if(x.mesh.type==='Group')x.mesh.children.forEach(function(c){c.userData.organId=x.id;candidates.push(c);});else candidates.push(x.mesh);}});var hit=raycaster.intersectObjects(candidates,false)[0];if(hit&&hit.object.userData.organId)selectOrgan(hit.object.userData.organId,true);}
  function updateLabels(){if(!camera)return;var show=dom.labelsToggle.checked;labels.forEach(function(x){var sys=organ(x.id).system,world=new THREE.Vector3();x.mesh.getWorldPosition(world);world.project(camera);x.el.style.left=((world.x+1)/2*dom.scene.clientWidth)+'px';x.el.style.top=((-world.y+1)/2*dom.scene.clientHeight)+'px';x.el.style.opacity=show&&systemGroups[sys].visible&&world.z<1?'1':'0';});}
  function resize(){if(!renderer)return;var w=dom.scene.clientWidth,h=dom.scene.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
  function animate(){animationId=requestAnimationFrame(animate);if(autoRotate&&!dragging)rotationY+=.0022;modelRoot.rotation.y=rotationY;modelRoot.rotation.x=rotationX;camera.position.set(0,1.3,distance);camera.lookAt(0,.8,0);renderer.render(scene,camera);updateLabels();}
  function bind(){document.querySelectorAll('[data-system]').forEach(function(b){b.addEventListener('click',function(){setFilter(b.dataset.system);});});dom.rotateButton.textContent=autoRotate?'⏸ Detener giro':'▶ Girar';dom.rotateButton.addEventListener('click',function(){autoRotate=!autoRotate;dom.rotateButton.textContent=autoRotate?'⏸ Detener giro':'▶ Girar';});dom.resetButton.addEventListener('click',function(){rotationX=-.08;rotationY=.25;distance=25;setFilter('all');});dom.bodyToggle.addEventListener('change',function(){if(bodyGroup)bodyGroup.visible=dom.bodyToggle.checked;});dom.opacityRange.addEventListener('input',function(){bodyMaterials.forEach(function(m){m.opacity=Number(dom.opacityRange.value);});});dom.labelsToggle.addEventListener('change',updateLabels);dom.journeyPrev.addEventListener('click',function(){if(state.journey>0){state.journey--;renderJourney();}});dom.journeyNext.addEventListener('click',function(){if(state.journey<JOURNEY.length-1){state.journey++;renderJourney();}else{state.journeyDone=true;save();dom.journeyText.textContent='✓ El oxígeno llegó a los tejidos y el circuito puede comenzar de nuevo.';}});addEventListener('resize',resize);addEventListener('pagehide',function(){if(animationId)cancelAnimationFrame(animationId);});}
  function start(){cache();bind();renderMission();renderQuestion();updateProgress();try{initThree();}catch(error){dom.fallback.hidden=false;console.warn('EduConect 3D fallback:',error.message);}renderOrganButtons();selectOrgan(state.selected,false);window.anatomyAtlasReady=true;}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
}());
