(function(){
  'use strict';
  const T=window.THREE;
  if(!T){document.getElementById('scene').textContent='No se pudo cargar el motor 3D local.';return;}
  const elements={H:{name:'Hidrógeno',color:0xf5f5f5,r:.43},O:{name:'Oxígeno',color:0xe74735,r:.62},C:{name:'Carbono',color:0x333b45,r:.6},N:{name:'Nitrógeno',color:0x3978de,r:.59}};
  const molecules={
    water:{name:'Agua',formula:'H₂O',geometry:'Angular (104,5°)',use:'Esencial para todos los seres vivos.',description:'Dos hidrógenos comparten electrones con un oxígeno.',atoms:[['O',0,0,0],['H',-1,.7,0],['H',1,.7,0]],bonds:[[0,1],[0,2]]},
    oxygen:{name:'Oxígeno',formula:'O₂',geometry:'Lineal',use:'Respiración celular y combustión.',description:'Dos átomos de oxígeno unidos mediante un enlace doble.',atoms:[['O',-.7,0,0],['O',.7,0,0]],bonds:[[0,1], [0,1,.13]]},
    carbon:{name:'Dióxido de carbono',formula:'CO₂',geometry:'Lineal (180°)',use:'Fotosíntesis y ciclo del carbono.',description:'Un carbono central enlazado con dos oxígenos.',atoms:[['O',-1.45,0,0],['C',0,0,0],['O',1.45,0,0]],bonds:[[0,1],[1,2]]},
    methane:{name:'Metano',formula:'CH₄',geometry:'Tetraédrica',use:'Combustible y producto de procesos biológicos.',description:'El carbono forma cuatro enlaces equivalentes.',atoms:[['C',0,0,0],['H',1,1,1],['H',-1,-1,1],['H',-1,1,-1],['H',1,-1,-1]],bonds:[[0,1],[0,2],[0,3],[0,4]]},
    ammonia:{name:'Amoníaco',formula:'NH₃',geometry:'Piramidal trigonal',use:'Producción de fertilizantes.',description:'Un nitrógeno unido a tres hidrógenos.',atoms:[['N',0,.35,0],['H',-1,-.6,.4],['H',1,-.6,.4],['H',0,-.6,-1]],bonds:[[0,1],[0,2],[0,3]]}
  };
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(45,1,.1,100),renderer=new T.WebGLRenderer({antialias:true,alpha:true});
  renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0x092b3a,1);document.getElementById('scene').appendChild(renderer.domElement);
  const group=new T.Group();scene.add(group);scene.add(new T.AmbientLight(0xffffff,.75));const light=new T.DirectionalLight(0xffffff,1);light.position.set(4,5,7);scene.add(light);camera.position.z=6;
  let current='water',auto=!matchMedia('(prefers-reduced-motion: reduce)').matches,drag=false,last={x:0,y:0},score=Number(localStorage.getItem('educonect-qui401-score')||0);
  document.getElementById('score').textContent=score;
  function atom(symbol,x,y,z,index){const info=elements[symbol],mesh=new T.Mesh(new T.SphereGeometry(info.r,28,20),new T.MeshPhongMaterial({color:info.color,shininess:80}));mesh.position.set(x,y,z);mesh.userData={symbol,index};return mesh}
  function bond(a,b,offset){const start=new T.Vector3(a[1],a[2]+(offset||0),a[3]),end=new T.Vector3(b[1],b[2]+(offset||0),b[3]),mid=start.clone().add(end).multiplyScalar(.5),dir=end.clone().sub(start);const mesh=new T.Mesh(new T.CylinderGeometry(.11,.11,dir.length(),14),new T.MeshPhongMaterial({color:0xa9bac1}));mesh.position.copy(mid);mesh.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),dir.normalize());return mesh}
  function clear(){while(group.children.length){const o=group.children.pop();o.geometry&&o.geometry.dispose();o.material&&o.material.dispose()}}
  function load(id){current=id;const m=molecules[id];clear();m.bonds.forEach(b=>group.add(bond(m.atoms[b[0]],m.atoms[b[1]],b[2])));m.atoms.forEach((a,i)=>group.add(atom(a[0],a[1],a[2],a[3],i)));group.rotation.set(.25,-.45,0);camera.position.z=6;['Name','formula','geometry','use','description'].forEach(k=>document.getElementById(k==='Name'?'moleculeName':k).textContent=m[k==='Name'?'name':k]);document.getElementById('atomFact').textContent='Toca un átomo para identificarlo.';document.querySelectorAll('.molecule').forEach(b=>b.classList.toggle('active',b.dataset.id===id));}
  function resize(){const host=document.getElementById('scene'),w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
  function select(clientX,clientY){const r=renderer.domElement.getBoundingClientRect(),mouse=new T.Vector2((clientX-r.left)/r.width*2-1,-(clientY-r.top)/r.height*2+1),ray=new T.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(group.children).find(x=>x.object.userData.symbol);if(!hit)return;const e=elements[hit.object.userData.symbol];document.getElementById('atomFact').textContent=`${e.name} (${hit.object.userData.symbol}) · átomo ${hit.object.userData.index+1}`;if(current==='water'&&hit.object.userData.symbol==='O'&&!document.getElementById('missionStatus').classList.contains('done')){score+=10;localStorage.setItem('educonect-qui401-score',score);document.getElementById('score').textContent=score;const s=document.getElementById('missionStatus');s.textContent='✓ ¡Misión cumplida!';s.classList.add('done')}}
  renderer.domElement.addEventListener('pointerdown',e=>{drag=true;last={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;group.rotation.y+=(e.clientX-last.x)*.01;group.rotation.x+=(e.clientY-last.y)*.01;last={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',e=>{if(Math.abs(e.clientX-last.x)<4&&Math.abs(e.clientY-last.y)<4)select(e.clientX,e.clientY);drag=false});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();camera.position.z=Math.max(3,Math.min(10,camera.position.z+Math.sign(e.deltaY)*.4))},{passive:false});
  document.querySelectorAll('.molecule').forEach(b=>b.onclick=()=>load(b.dataset.id));document.getElementById('rotate').onclick=e=>{auto=!auto;e.currentTarget.textContent=auto?'⏸ Pausar':'▶ Girar'};document.getElementById('zoomIn').onclick=()=>camera.position.z=Math.max(3,camera.position.z-.5);document.getElementById('zoomOut').onclick=()=>camera.position.z=Math.min(10,camera.position.z+.5);document.getElementById('reset').onclick=()=>load(current);
  document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='carbon';document.querySelectorAll('[data-answer]').forEach(x=>x.classList.remove('correct','wrong'));b.classList.add(ok?'correct':'wrong');document.getElementById('quizFeedback').textContent=ok?'✓ Correcto: O=C=O forma una línea de 180°.':'Aún no. Observa las geometrías en la ficha científica.'});
  window.addEventListener('resize',resize);load(current);resize();(function frame(){requestAnimationFrame(frame);if(auto&&!drag)group.rotation.y+=.004;renderer.render(scene,camera)})();window.molecularLabReady=true;
})();
